### ISSUE TITLE
error of duplicate sample names

### ISSUE THREAD

**Issue by valdirbarth** [mretier/growthdash#33]
I am constantly getting the "Duplicate sample names are not allowed, please make sure that each sample is associated with a unique name and/or indicate replicates with digits (e.g. " test_sample 1")." error.
I have double checked the names of my samples plus replicates, and they are not duplicated.
I am attaching one example.

Nevermind, I found the issue :)

**Comment by valdirbarth** [comment]
I found the issue in my file.

**Comment by mretier** [comment]
happy to hear that you could resolve the issue.
