### ISSUE TITLE
Application failing

### ISSUE THREAD

**Issue by HSMSC** [mretier/growthdash#34]
I have 2 samples, 48 replicates per sample, and no blanks, measured every 5 minutes over 48 hours (hoping to subtract the first measurement as the blank).

When I drop the file in the web application, the page freezes and fails. It says it can not display the webpage.

Question:

1-Could it be due to something wrong with my data file, like the replicates being named the same?

Thanks!

**Comment by mretier** [comment]
Hi, 
Thanks for using the app!
If you download the sample file you should get a good idea of how the replicates should be named. If that doesn't help, I can troubleshoot. Would it be possible to share your file? That would make it easiest.

**Comment by HSMSC** [comment]
The file was not semicolon separated. I converted it and its working now! Thank you!
